### ISSUE TITLE
"Activity by the user last 12 months" options not displaying

### ISSUE THREAD

**Issue by NilsTheBest** [scratchuserstats/scratchstats#33]
Not sure if it just hasn't been made yet, but it appears that some options in the section "Activity by the user last 12 months" aren't displaying properly. Here's a screenshot of the issue:
![bugmaybe](https://user-images.githubusercontent.com/41824646/46968838-965a6f80-d0b4-11e8-89f3-4d9374373f40.png)
Any ways it could be fixed? Thanks!

**Comment by WorldLanguages** [comment]
Question marks are a feature - the activity API is always in the native language of the user, so we display question marks if it's not English and cannot search for the words "shared", "followed", etc. We do a workaround with loves and faves by searching the icons. But users and studios followed have the same icon.

Can you go to this URL and tell me if it's English? https://scratch.mit.edu/messages/ajax/user-activity/?user=World_Languages&max=10

**Comment by WorldLanguages** [comment]
Wait, actually, I get that in English because it's the language I set on Scratch, but when scratchstats requests that URL I get it in Spanish (I'm from Argentina). Can you look at the Network tab on ScratchStats if it's English?

**Comment by WorldLanguages** [comment]
@NilsTheBest Yay, now the row works for all computers (even mine). I made it so the activity request to the API goes to a CORS proxy that always returns the result in English! :)

Apparently even users from the US were seeing question marks because someone missed adding ".length" somewhere in the code, and I never noticed because question marks were intended for users like me that did not load the activity in English. But now it will always return in English, so issue solved! Thanks for bringing this up.
